version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: fpo-api
    restart: unless-stopped
    env_file: .env
    ports:
      # local->container
      - $NODE_PORT:$NODE_PORT
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - TZ=Europe/Kiev

  client:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: fpo-client
    stdin_open: true
    tty: true
    ports:
      # local->container
      - '5000:5000'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Europe/Kiev
    depends_on:
      - server
