version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: server
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      # local->container
      - 4000:4000
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - TZ=Europe/Kiev

  client:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: client
    stdin_open: true
    tty: true
    ports:
      # local->container
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Europe/Kiev
    depends_on:
      - server
